name: Hellow Flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hellow World!"
      - name: Diga valeu
        run: echo "Valeu - bye!"
