name: Hellow Flow
on:
  push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hellow World!"
      - name: Diga valeu
        run: echo "Valeu - bye!"
